package v1alpha1

import (
	"testing"
)

var (
	expectedConfigEmpty = `
# Config generated by mariadb-operator

[mysqld]
wsrep-new-cluster = yes
`
	expectedConfigWSREP = `
# Config generated by mariadb-operator

[mysqld]
wsrep_cluster_address = gcomm://mariadb-0,gcomm://mariadb-1
`
)

func TestConfigTemplates(t *testing.T) {
	conf := &MariaDBConfig{}
	output, err := conf.Render()
	if err != nil || output != expectedConfigEmpty {
		t.Fail()
	}
	t.Logf("Output Empty: \n%s", output)

	conf = &MariaDBConfig{
		WSREPEndpoints: []string{"mariadb-0", "mariadb-1"},
	}
	output, err = conf.Render()
	if err != nil || output != expectedConfigWSREP {
		t.Fail()
	}
	t.Logf("Output WSREP : \n%s", output)

}
