// +build !ignore_autogenerated

/*
Copyright 2018 The mariadb-operator Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBCluster) DeepCopyInto(out *MariaDBCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBCluster.
func (in *MariaDBCluster) DeepCopy() *MariaDBCluster {
	if in == nil {
		return nil
	}
	out := new(MariaDBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MariaDBCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBClusterCondition) DeepCopyInto(out *MariaDBClusterCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBClusterCondition.
func (in *MariaDBClusterCondition) DeepCopy() *MariaDBClusterCondition {
	if in == nil {
		return nil
	}
	out := new(MariaDBClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBClusterList) DeepCopyInto(out *MariaDBClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MariaDBCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBClusterList.
func (in *MariaDBClusterList) DeepCopy() *MariaDBClusterList {
	if in == nil {
		return nil
	}
	out := new(MariaDBClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MariaDBClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBClusterSpec) DeepCopyInto(out *MariaDBClusterSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.Storages = in.Storages
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBClusterSpec.
func (in *MariaDBClusterSpec) DeepCopy() *MariaDBClusterSpec {
	if in == nil {
		return nil
	}
	out := new(MariaDBClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBClusterStatus) DeepCopyInto(out *MariaDBClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]MariaDBClusterCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StatefulSetPodConditions != nil {
		in, out := &in.StatefulSetPodConditions, &out.StatefulSetPodConditions
		*out = make([]PodCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBClusterStatus.
func (in *MariaDBClusterStatus) DeepCopy() *MariaDBClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MariaDBClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBConfig) DeepCopyInto(out *MariaDBConfig) {
	*out = *in
	if in.WSREPEndpoints != nil {
		in, out := &in.WSREPEndpoints, &out.WSREPEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBConfig.
func (in *MariaDBConfig) DeepCopy() *MariaDBConfig {
	if in == nil {
		return nil
	}
	out := new(MariaDBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseVars) DeepCopyInto(out *PhaseVars) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseVars.
func (in *PhaseVars) DeepCopy() *PhaseVars {
	if in == nil {
		return nil
	}
	out := new(PhaseVars)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCondition) DeepCopyInto(out *PodCondition) {
	*out = *in
	in.Reported.DeepCopyInto(&out.Reported)
	out.GRAState = in.GRAState
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCondition.
func (in *PodCondition) DeepCopy() *PodCondition {
	if in == nil {
		return nil
	}
	out := new(PodCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConditionGRAState) DeepCopyInto(out *PodConditionGRAState) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConditionGRAState.
func (in *PodConditionGRAState) DeepCopy() *PodConditionGRAState {
	if in == nil {
		return nil
	}
	out := new(PodConditionGRAState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storages) DeepCopyInto(out *Storages) {
	*out = *in
	out.Data = in.Data
	out.Snapshot = in.Snapshot
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storages.
func (in *Storages) DeepCopy() *Storages {
	if in == nil {
		return nil
	}
	out := new(Storages)
	in.DeepCopyInto(out)
	return out
}
